import React from 'react';

// ** Custom Components
import {theme as AppTheme} from '../../infrustructure/theme';

// ** Skeleton
import SkeletonPlaceholder from 'react-native-skeleton-placeholder';

const SpeedometerSkeleton = () => {
  return (
    <SkeletonPlaceholder
      borderRadius={4}
      enabled={true}
      speed={1000}
      backgroundColor={AppTheme.DefaultPalette().skeleton.backgroundColor}
      highlightColor={AppTheme.DefaultPalette().skeleton.highlightColor}>
      <SkeletonPlaceholder.Item
        flexDirection="column"
        alignItems="center"
        marginTop={AppTheme.WP(5)}
        justifyContent={'center'}>
        <SkeletonPlaceholder.Item
          width={AppTheme.WP(50)}
          height={AppTheme.WP(3)}
        />

        <SkeletonPlaceholder.Item
          flexDirection="row"
          alignItems="flex-start"
          marginTop={AppTheme.WP(5)}
          justifyContent={'center'}>
          <SkeletonPlaceholder.Item
            flexDirection="column"
            alignItems="center"
            width={'20%'}
            marginHorizontal={AppTheme.WP(2)}
            // marginTop={AppTheme.WP(5)}
            justifyContent={'flex-start'}>
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(18)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(10)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(10)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(8)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(3)}
              marginTop={AppTheme.WP(9)}
            />
          </SkeletonPlaceholder.Item>

          <SkeletonPlaceholder.Item
            flexDirection="column"
            alignItems="center"
            width={'20%'}
            marginHorizontal={AppTheme.WP(2)}
            marginTop={AppTheme.WP(5)}
            justifyContent={'flex-start'}>
            <SkeletonPlaceholder.Item
              flexDirection="row"
              alignItems="center"
              marginBottom={AppTheme.WP(2)}
              justifyContent={'center'}>
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(6)}
                height={AppTheme.WP(6)}
                marginRight={AppTheme.WP(1)}
                borderRadius={AppTheme.WP(30)}
              />
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(10)}
                height={AppTheme.WP(3)}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
          </SkeletonPlaceholder.Item>

          <SkeletonPlaceholder.Item
            flexDirection="column"
            alignItems="center"
            width={'20%'}
            marginHorizontal={AppTheme.WP(2)}
            marginTop={AppTheme.WP(5)}
            justifyContent={'flex-start'}>
            <SkeletonPlaceholder.Item
              flexDirection="row"
              alignItems="center"
              marginBottom={AppTheme.WP(2)}
              justifyContent={'center'}>
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(6)}
                height={AppTheme.WP(6)}
                marginRight={AppTheme.WP(1)}
                borderRadius={AppTheme.WP(30)}
              />
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(10)}
                height={AppTheme.WP(3)}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
          </SkeletonPlaceholder.Item>

          <SkeletonPlaceholder.Item
            flexDirection="column"
            alignItems="center"
            width={'20%'}
            marginHorizontal={AppTheme.WP(2)}
            marginTop={AppTheme.WP(5)}
            justifyContent={'flex-start'}>
            <SkeletonPlaceholder.Item
              flexDirection="row"
              alignItems="center"
              marginBottom={AppTheme.WP(2)}
              justifyContent={'center'}>
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(6)}
                height={AppTheme.WP(6)}
                marginRight={AppTheme.WP(1)}
                borderRadius={AppTheme.WP(30)}
              />
              <SkeletonPlaceholder.Item
                width={AppTheme.WP(10)}
                height={AppTheme.WP(3)}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
            <SkeletonPlaceholder.Item
              width={AppTheme.WP(10)}
              height={AppTheme.WP(10)}
              marginTop={AppTheme.WP(2)}
              borderRadius={AppTheme.WP(30)}
            />
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder.Item>
    </SkeletonPlaceholder>
  );
};
export {SpeedometerSkeleton};
